-- iService Request Data Backup
-- Created  : 2026-02-27 06:09:55
-- Tables   : task_history, task_assignments, request_email_details, request_internet_details, request_it_support_details, request_led_details, request_mc_details, request_nas_details, request_photography_details, request_printer_details, request_qrcode_details, request_webdesign_details, service_requests
-- Restore  : run via admin > ตั้งค่าระบบ > จัดการข้อมูล > Restore
------------------------------------------------------------

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table: service_requests (26 rows)
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('1', '1', 'REQ-2025-0001', 'EMAIL', 'ขอใช้บริการ Email', NULL, 'สมชาย ใจดี', 'เจ้าหน้าที่', '081-234-5678', 'somchai@temp.mail', '32', 'ฝ่ายบริหาร', 'ขอใช้บริการ Email - สมชาย ใจดี', 'ต้องการอีเมลสำหรับงานราชการ', NULL, 'pending', 'medium', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-12-29 15:26:54', '2026-01-05 16:53:36', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('2', '9', 'REQ-2025-0002', 'PRINTER', 'ขอใช้เครื่องพิมพ์', NULL, 'วิภา สุขสันต์', NULL, '089-876-5432', 'wipa@rangsit.go.th', '33', 'ฝ่ายการเงิน', 'ขอใช้เครื่องพิมพ์ - วิภา สุขสันต์', 'เครื่องพิมพ์เอกสารไม่ออก', NULL, 'in_progress', 'high', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-12-29 15:26:54', '2026-01-05 16:53:43', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('3', '8', 'REQ-2025-0003', 'PHOTOGRAPHY', 'ขอถ่ายภาพกิจกรรม', NULL, 'ประสิทธิ์ วงศ์ดี', NULL, NULL, 'prasit@rangsit.go.th', '34', 'ฝ่ายประชาสัมพันธ์', 'ขอถ่ายภาพกิจกรรม - ประสิทธิ์ วงศ์ดี', 'งานประชุมคณะกรรมการ', NULL, 'pending', 'medium', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-12-29 15:26:54', '2026-01-05 16:53:49', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('4', '7', 'REQ-2025-0004', 'EMAIL', 'ขอใช้บริการ Email', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '35', 'งานพัฒนาและส่งเสริมการท่องเที่ยว', 'ขอใช้บริการ Email - ทนงค์ บุญเติม', '', NULL, 'pending', 'low', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-12-30 11:05:03', '2026-01-05 16:53:29', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('5', '7', 'REQ-2025-0005', 'EMAIL', 'ขอใช้บริการ Email', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '3', 'สำนักช่าง', 'ขอใช้บริการ Email - ทนงค์ บุญเติม', 'eeeeeeeeeeeeeee', NULL, 'pending', 'low', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-12-30 15:01:10', '2026-01-05 16:53:22', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('7', NULL, 'REQ-2026-0001', 'MC', 'ขอพธกร', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '27', 'งานพัฒนาและส่งเสริมการท่องเที่ยว', 'ขอพธกร Request from ทนงค์ บุญเติม', 'test', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-02 18:39:50', '2026-02-02 18:39:50', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('8', NULL, 'REQ-2026-0002', 'MC', 'ขอพธกร', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '27', 'งานพัฒนาและส่งเสริมการท่องเที่ยว', 'ขอพธกร Request from ทนงค์ บุญเติม', 'test', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-02 18:41:26', '2026-02-02 18:41:26', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('9', NULL, 'REQ-2026-0003', 'EMAIL', 'อีเมลเทศบาล', NULL, 'test D tester', 'test', '012345678998', 'kongpop.chok@gmail.com', '8', 'กองยุทธศาสตร์และงบประมาณ', 'อีเมลเทศบาล Request from test D tester', 'test', NULL, 'completed', 'medium', NULL, NULL, '', NULL, NULL, NULL, NULL, '2026-02-04 14:43:35', NULL, '2026-02-04 14:41:33', '2026-02-04 14:43:35', '[\"storage\\/uploads\\/requests\\/2026\\/02\\/REQ_6982f82d0c1b58.49435922.jpg\"]');
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('16', NULL, 'REQ-2026-0004', 'IT_SUPPORT', 'แจ้งซ่อมระบบ IT', NULL, 'test D tester', 'test', '0640945941', 'kongpop.chok@gmail.com', '8', 'กองยุทธศาสตร์และงบประมาณ', 'แจ้งซ่อมระบบ IT Request from test D tester', 'test', NULL, 'pending', 'high', NULL, NULL, NULL, NULL, NULL, '2569-02-16', NULL, NULL, NULL, '2026-02-04 15:18:17', '2026-02-04 15:18:17', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('23', NULL, 'REQ-2026-0005', 'PRINTER', 'เครื่องพิมพ์และสแกนเนอร์', NULL, 'test D tester', 'test', '0640945941', 'kongpop.chok@gmail.com', '8', 'กองยุทธศาสตร์และงบประมาณ', 'เครื่องพิมพ์และสแกนเนอร์ Request from test D tester', 'test', NULL, 'pending', 'urgent', NULL, NULL, NULL, NULL, NULL, '2569-03-13', NULL, NULL, NULL, '2026-02-04 15:33:25', '2026-02-04 15:33:25', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('24', NULL, 'REQ-2026-0006', 'MC', 'ขอพธกร', NULL, 'test D tester', 'test', '0640945941', 'kongpop.chok@gmail.com', '8', 'กองยุทธศาสตร์และงบประมาณ', 'ขอพธกร Request from test D tester', 'test', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-04 15:34:48', '2026-02-04 15:34:48', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('27', NULL, 'REQ-2026-0007', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักส่งเสริมการพัฒนาเมือง', '0910109174', 'thanongb42@gmail.com', '157', 'งานส่งเสริมการพัฒนาเมือง', 'บริการถ่ายภาพ Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, '2026-02-06', NULL, NULL, NULL, '2026-02-05 11:28:55', '2026-02-05 11:28:55', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('28', NULL, 'REQ-2026-0008', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักส่งเสริมการพัฒนาเมือง', '0910109174', 'thanongb42@gmail.com', '157', 'งานส่งเสริมการพัฒนาเมือง', 'บริการถ่ายภาพ Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, '2026-02-06', NULL, NULL, NULL, '2026-02-05 11:29:00', '2026-02-05 11:29:00', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('29', NULL, 'REQ-2026-0009', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักส่งเสริมการพัฒนาเมือง', '0910109174', 'thanongb42@gmail.com', '157', 'งานส่งเสริมการพัฒนาเมือง', 'บริการถ่ายภาพ Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, '2026-02-06', NULL, NULL, NULL, '2026-02-05 11:30:42', '2026-02-05 11:30:42', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('30', NULL, 'REQ-2026-0010', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักส่งเสริมการพัฒนาเมือง', '0910109174', 'thanongb42@gmail.com', '157', 'งานส่งเสริมการพัฒนาเมือง', 'บริการถ่ายภาพ Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'completed', 'medium', '11', NULL, NULL, NULL, NULL, '2026-02-06', NULL, '2026-02-05 14:27:11', NULL, '2026-02-05 11:32:05', '2026-02-05 14:27:11', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('31', NULL, 'REQ-2026-0011', 'MC', 'ขอพิธีกร', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักส่งเสริมการพัฒนาเมือง', '0910109174', 'thanongb42@gmail.com', '123', 'งานบริหารวิชาการ', 'ขอพิธีกร Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-05 16:42:25', '2026-02-05 16:42:25', '[\"storage\\/uploads\\/requests\\/2026\\/02\\/REQ_69846601dbba96.54801507.jpg\"]');
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('32', NULL, 'REQ-2026-0012', 'INTERNET', 'อินเทอร์เน็ต / WiFi', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักวิเคราะห์นโยบายและแผน', '0910109174', 'thanongb42@gmail.com', '88', 'งานกำจัดขยะมูลฝอยและสิ่งปฏิกูล', 'อินเทอร์เน็ต / WiFi Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-05 17:23:00', '2026-02-05 17:23:00', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('33', NULL, 'REQ-2026-0013', 'INTERNET', 'อินเทอร์เน็ต / WiFi', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักวิเคราะห์นโยบายและแผน', '0910109174', 'thanongb42@gmail.com', '88', 'งานกำจัดขยะมูลฝอยและสิ่งปฏิกูล', 'อินเทอร์เน็ต / WiFi Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'completed', 'medium', NULL, NULL, '', NULL, NULL, NULL, NULL, '2026-02-06 15:54:48', NULL, '2026-02-05 17:23:13', '2026-02-06 15:54:48', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('34', NULL, 'REQ-2026-0014', 'INTERNET', 'อินเทอร์เน็ต / WiFi', NULL, 'นายคิดวิเคราะห์  แยกแยะ', 'นักวิเคราะห์นโยบายและแผน', '0910109174', 'thanongb42@gmail.com', '88', 'งานกำจัดขยะมูลฝอยและสิ่งปฏิกูล', 'อินเทอร์เน็ต / WiFi Request from นายคิดวิเคราะห์  แยกแยะ', '', NULL, 'completed', 'medium', '1', NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-06 11:42:19', NULL, '2026-02-05 17:24:41', '2026-02-06 11:42:19', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('35', NULL, 'REQ-2026-0015', 'EMAIL', 'อีเมลเทศบาล', NULL, 'นางอังเคิล มาเกตาร์', 'นักวิชาการเงินการคลัง', '0940400098', 'Angcle@gmail.com', '57', 'งานการเงินและบัญชี', 'อีเมลเทศบาล Request from นางอังเคิล มาเกตาร์', '', NULL, 'completed', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-06 14:07:38', NULL, '2026-02-06 11:47:15', '2026-02-06 14:07:38', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('37', NULL, 'REQ-2026-0016', 'NAS', 'พื้นที่เก็บข้อมูล NAS', NULL, 'นายถ่าน มืดมิด', 'นักวิชาการคอมพิวเตอร์', '0940400098', 'thanong@rangsitcity.go.th', '159', 'งานสถิติข้อมูลและสารสนเทศ', 'พื้นที่เก็บข้อมูล NAS Request from นายถ่าน มืดมิด', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, '2026-02-06', NULL, NULL, NULL, '2026-02-06 16:04:56', '2026-02-06 16:04:56', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('38', NULL, 'REQ-2026-0017', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'นายสมใจ ไม้งาม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '140', 'งานบริหารงานทั่วไป', 'บริการถ่ายภาพ Request from นายสมใจ ไม้งาม', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, '2026-02-26', NULL, NULL, NULL, '2026-02-26 08:50:14', '2026-02-26 08:50:14', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('39', NULL, 'REQ-2026-0018', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '161', 'งานบริหารงานทั่วไป (กจ)', 'บริการถ่ายภาพ Request from ทนงค์ บุญเติม', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-26 09:20:18', '2026-02-26 09:20:18', '[\"storage\\/uploads\\/requests\\/2026\\/02\\/REQ_699fade20428e7.81925114.png\"]');
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('40', NULL, 'REQ-2026-0019', 'PHOTOGRAPHY', 'บริการถ่ายภาพ', NULL, 'ทนงค์ บุญเติม', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '161', 'งานบริหารงานทั่วไป (กจ)', 'บริการถ่ายภาพ Request from ทนงค์ บุญเติม', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-26 09:22:55', '2026-02-26 09:22:55', '[\"storage\\/uploads\\/requests\\/2026\\/02\\/REQ_699fae7faa0908.28296395.png\"]');
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('41', NULL, 'REQ-2026-0020', 'MC', 'ขอพิธีกร', NULL, 'นายสมใจ ไม้งาม', 'ผู้ช่วยนักจัดการงานทั่วไป', '0910109174', 'thanongb42@gmail.com', '160', 'งานขอรับการจัดสรรเงินอุดหนุน', 'ขอพิธีกร Request from นายสมใจ ไม้งาม', '', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-26 09:53:57', '2026-02-26 09:53:57', NULL);
INSERT INTO `service_requests` (`request_id`, `user_id`, `request_code`, `service_code`, `service_name`, `requester_prefix_id`, `requester_name`, `requester_position`, `requester_phone`, `requester_email`, `department_id`, `department_name`, `subject`, `description`, `request_data`, `status`, `priority`, `assigned_to`, `assigned_at`, `admin_notes`, `rejection_reason`, `completion_notes`, `expected_completion_date`, `started_at`, `completed_at`, `cancelled_at`, `created_at`, `updated_at`, `attachments`) VALUES ('42', NULL, 'REQ-2026-0021', 'INTERNET', 'อินเทอร์เน็ต / WiFi', '2', '0', 'นักวิชาการคอมพิวเตอร์ปฏิบัติการ', '0910109174', 'thanongb42@gmail.com', '12', 'กลุ่มงานบริหารงานทั่วไป(สป)', 'อินเทอร์เน็ต / WiFi Request from นางTHANONG BOONTERM', '11111', NULL, 'pending', 'medium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-27 11:00:43', '2026-02-27 11:00:43', '[\"storage\\/uploads\\/requests\\/2026\\/02\\/REQ_69a116eb558382.59265921.png\"]');

-- Table `request_webdesign_details` is empty

-- Table `request_qrcode_details` is empty

-- Table: request_printer_details (2 rows)
INSERT INTO `request_printer_details` (`id`, `request_id`, `issue_type`, `printer_type`, `printer_brand`, `printer_model`, `serial_number`, `location`, `problem_description`, `error_code`, `toner_color`, `supplies_needed`) VALUES ('1', '2', 'repair', 'laser', 'HP', 'LaserJet Pro M404', NULL, 'อาคาร 2 ชั้น 3 ห้องการเงิน', 'เครื่องพิมพ์เปิดไฟได้ แต่พิมพ์เอกสารไม่ออก มีไฟกระพริบสีแดง', NULL, NULL, NULL);
INSERT INTO `request_printer_details` (`id`, `request_id`, `issue_type`, `printer_type`, `printer_brand`, `printer_model`, `serial_number`, `location`, `problem_description`, `error_code`, `toner_color`, `supplies_needed`) VALUES ('2', '23', 'toner_replacement', 'plotter', 'Test', 'test', 'test', 'test', 'test', 'test', 'test', 'test');

-- Table: request_photography_details (8 rows)
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('1', '3', 'การประชุมคณะกรรมการเทศบาล ครั้งที่ 1/2568', 'ประชุม', '2025-01-15', '09:00:00', '16:00:00', 'ห้องประชุมใหญ่ ชั้น 5', '1', '1', '0', 'Digital (Drive)', NULL);
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('2', '27', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-06', '09:30:00', '12:00:00', '0', '1', '0', '0', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('3', '28', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-06', '09:30:00', '12:00:00', '0', '1', '0', '0', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('4', '29', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-06', '09:30:00', '12:00:00', '0', '1', '0', '0', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('5', '30', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-07', '08:31:00', '00:32:00', '0', '1', '1', '1', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('6', '38', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-27', '10:45:00', '00:00:00', '0', '1', '1', '0', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('7', '39', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-27', '00:00:00', '00:00:00', '0', '1', '0', '0', 'Digital (Google Drive)', '');
INSERT INTO `request_photography_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `event_location`, `number_of_photographers`, `video_required`, `drone_required`, `delivery_format`, `special_requirements`) VALUES ('8', '40', 'เทศบาลเคลื่อนที่', 'งานกิจกรรม', '2026-02-27', '11:00:00', '15:50:00', '0', '1', '1', '0', 'Digital (Google Drive)', '');

-- Table: request_nas_details (1 rows)
INSERT INTO `request_nas_details` (`id`, `request_id`, `folder_name`, `storage_size_gb`, `permission_type`, `shared_with`, `purpose`, `backup_required`) VALUES ('1', '37', 'photography', '10', 'read_write', '', 'เก็บงาน', '1');

-- Table: request_mc_details (5 rows)
INSERT INTO `request_mc_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `location`, `mc_count`, `language`, `script_status`, `dress_code`, `note`) VALUES ('1', '7', 'เทศบาลเคลื่อนที่', 'formal', '2026-02-07', '19:35:00', '12:00:00', 'กองยุทธศาวตร์และงบประมาณ', '1', 'TH', 'not_ready', '', 'test');
INSERT INTO `request_mc_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `location`, `mc_count`, `language`, `script_status`, `dress_code`, `note`) VALUES ('2', '8', 'เทศบาลเคลื่อนที่', 'formal', '2026-02-07', '19:35:00', '12:00:00', 'กองยุทธศาวตร์และงบประมาณ', '1', 'TH', 'not_ready', '', 'test');
INSERT INTO `request_mc_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `location`, `mc_count`, `language`, `script_status`, `dress_code`, `note`) VALUES ('3', '24', 'test งานประชุม', 'formal', '2569-03-01', '09:00:00', '12:00:00', 'test ห้องนครรังสิต', '1', 'TH', 'not_ready', 'test', 'test');
INSERT INTO `request_mc_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `location`, `mc_count`, `language`, `script_status`, `dress_code`, `note`) VALUES ('4', '31', 'เทศบาลเคลื่อนที่', 'formal', '2026-02-09', '20:41:00', '14:41:00', 'ห้องหงษ์มังกร', '1', 'TH', 'not_ready', 'ผ้าไทยสีดำ', '');
INSERT INTO `request_mc_details` (`id`, `request_id`, `event_name`, `event_type`, `event_date`, `event_time_start`, `event_time_end`, `location`, `mc_count`, `language`, `script_status`, `dress_code`, `note`) VALUES ('5', '41', 'เทศบาลเคลื่อนที่', 'formal', '2026-02-28', '10:40:00', '11:55:00', 'กองยุทธศาวตร์และงบประมาณ', '1', 'TH', 'draft', 'ผ้าไทยสีดำ', '');

-- Table `request_led_details` is empty

-- Table: request_it_support_details (1 rows)
INSERT INTO `request_it_support_details` (`id`, `request_id`, `issue_type`, `device_type`, `device_brand`, `symptoms`, `location`, `urgency_level`, `error_message`, `when_occurred`) VALUES ('1', '16', 'network', 'test คอม', 'ASUS', 'test ไม่มีเน็ต', 'RSSC', 'low', '', 'test 2สัปดาห์');

-- Table: request_internet_details (4 rows)
INSERT INTO `request_internet_details` (`id`, `request_id`, `request_type`, `location`, `building`, `room_number`, `current_issue`, `citizen_id`) VALUES ('1', '32', 'new_wifi', 'ชั้น 4', '', '', '', NULL);
INSERT INTO `request_internet_details` (`id`, `request_id`, `request_type`, `location`, `building`, `room_number`, `current_issue`, `citizen_id`) VALUES ('2', '33', 'new_wifi', 'ชั้น 4', '', '', '', NULL);
INSERT INTO `request_internet_details` (`id`, `request_id`, `request_type`, `location`, `building`, `room_number`, `current_issue`, `citizen_id`) VALUES ('3', '34', 'new_wifi', 'ชั้น 4', '', '', '', NULL);
INSERT INTO `request_internet_details` (`id`, `request_id`, `request_type`, `location`, `building`, `room_number`, `current_issue`, `citizen_id`) VALUES ('4', '42', 'new_wifi', 'กองยุทธศาวตร์และงบประมาณ', '', '', 'rrrr', '1341100083508');

-- Table: request_email_details (2 rows)
INSERT INTO `request_email_details` (`id`, `request_id`, `requested_username`, `email_format`, `quota_mb`, `purpose`, `is_new_account`, `existing_email`) VALUES ('1', '9', 'test D tester', 'awd', '2048', 'test', '1', '');
INSERT INTO `request_email_details` (`id`, `request_id`, `requested_username`, `email_format`, `quota_mb`, `purpose`, `is_new_account`, `existing_email`) VALUES ('2', '35', 'Ancle maleta', 'ancle.m@rangsitcity.co.th', '2048', 'ใช้มนราชการ', '1', '');

-- Table: task_assignments (6 rows)
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('1', '30', '11', '4', '7', 'completed', 'normal', '2026-02-06 11:47:00', '', '2026-02-05 11:49:50', '2026-02-05 11:51:31', '2026-02-07 08:31:00', '2026-02-05 14:27:11', '2026-02-07 00:32:00', NULL, '2026-02-05 11:47:18', '2026-02-05 14:27:11');
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('2', '34', '7', '3', '7', 'completed', 'normal', '2026-02-06 09:00:00', '', '2026-02-06 11:03:02', '2026-02-06 11:41:02', NULL, '2026-02-06 11:42:19', NULL, NULL, '2026-02-05 18:36:52', '2026-02-06 11:42:19');
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('3', '35', '7', '3', '7', 'completed', 'normal', '2026-02-10 12:00:00', '', '2026-02-06 13:36:57', '2026-02-06 13:59:55', NULL, '2026-02-06 14:07:38', NULL, NULL, '2026-02-06 11:48:17', '2026-02-06 14:07:38');
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('7', '33', '7', NULL, '1', 'completed', 'normal', '2026-02-12 14:23:00', '', '2026-02-06 15:29:22', '2026-02-06 15:54:09', NULL, '2026-02-06 15:54:48', NULL, NULL, '2026-02-06 14:32:41', '2026-02-06 15:54:48');
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('8', '32', '11', NULL, '7', 'pending', 'normal', '0000-00-00 00:00:00', '', NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-06 17:56:44', '2026-02-06 17:56:44');
INSERT INTO `task_assignments` (`assignment_id`, `request_id`, `assigned_to`, `assigned_as_role`, `assigned_by`, `status`, `priority`, `due_date`, `notes`, `accepted_at`, `started_at`, `start_time`, `completed_at`, `end_time`, `completion_notes`, `created_at`, `updated_at`) VALUES ('9', '37', '11', NULL, '7', 'pending', 'normal', '0000-00-00 00:00:00', '', NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-06 17:57:51', '2026-02-06 17:57:51');

-- Table: task_history (11 rows)
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('1', '1', 'status_change', 'completed', 'completed', '11', '0', '2026-02-05 14:27:11');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('2', '2', 'status_change', 'pending', 'accepted', '7', '0', '2026-02-06 11:03:02');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('3', '2', 'status_change', 'accepted', 'in_progress', '7', '0', '2026-02-06 11:41:02');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('4', '2', 'status_change', 'in_progress', 'completed', '7', '0', '2026-02-06 11:42:19');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('5', '3', 'reassigned', NULL, NULL, '1', 'เปลี่ยนผู้รับผิดชอบจาก #7 เป็น #7. ผิดคน', '2026-02-06 13:34:23');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('6', '3', 'status_change', 'pending', 'accepted', '7', '0', '2026-02-06 13:36:57');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('7', '3', 'status_change', 'accepted', 'in_progress', '7', '0', '2026-02-06 13:59:55');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('8', '3', 'status_change', 'in_progress', 'completed', '7', '0', '2026-02-06 14:07:38');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('9', '7', 'status_change', 'pending', 'accepted', '7', '0', '2026-02-06 15:29:22');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('10', '7', 'status_change', 'accepted', 'in_progress', '7', '0', '2026-02-06 15:54:09');
INSERT INTO `task_history` (`id`, `assignment_id`, `action`, `old_status`, `new_status`, `performed_by`, `notes`, `created_at`) VALUES ('11', '7', 'status_change', 'in_progress', 'completed', '7', '0', '2026-02-06 15:54:48');

SET FOREIGN_KEY_CHECKS = 1;
-- END OF BACKUP (total rows: 66)
