-- ตารางเก็บข้อมูล PM2.5
CREATE TABLE IF NOT EXISTS pm25_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cid VARCHAR(32) NOT NULL,
    pm25 INT NOT NULL,
    co2 INT DEFAULT NULL,
    pm1 INT DEFAULT NULL,
    pm10 INT DEFAULT NULL,
    pm4 INT DEFAULT NULL,
    sensor_timestamp INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);